apiVersion: v1
kind: ServiceAccount
metadata:
  name: redshiftsink-operator
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: redshiftsink-operator
 namespace: kube-system
 labels:
   app: redshiftsink-operator
spec:
 strategy:
   type: Recreate
 replicas: 1
 selector:
   matchLabels:
     app: redshiftsink-operator
 template:
   metadata:
     labels:
       app: redshiftsink-operator
   spec:
     serviceAccountName: redshiftsink-operator
     tolerations:
     - effect: NoExecute
       operator: Exists
     - effect: NoSchedule
       operator: Exists
     volumes:
     - name: redshiftsink-secret-volume
       secret:
         secretName: redshiftsink-secret
     containers:
     - name: rsk-operator
       image: public.ecr.aws/practo/redshiftsink:v1.0.0-beta.5
       imagePullPolicy: Always
       volumeMounts:
       - name: redshiftsink-secret-volume
         mountPath: /secret.yaml
       command:
       - /redshiftsink
       args:
       - -v=2
       - --default-batcher-image=public.ecr.aws/practo/redshiftbatcher:v1.0.0-beta.5
       - --default-loader-image=public.ecr.aws/practo/redshiftloader:v1.0.0-beta.5
       - --default-redshift-max-open-conns=10
       - --default-redshift-max-idle-conns=2
       - --allowed-rsks=
       - --promethus-url=
       - --collect-redshift-metrics=false
       - --databases=
       resources:
         limits:
           cpu: 300m
           memory: 300Mi
         requests:
           cpu: 100m
           memory: 200Mi
