language: go
go:
- "1.17.1"
services:
  - docker
script:
- make build
- test -f bin/linux_amd64/redshiftbatcher
- test -f bin/linux_amd64/redshiftloader
- test -f bin/linux_amd64/redshiftsink
- make all-container
- docker images | grep "^public.ecr.aws/practo/redshiftbatcher"
- docker images | grep "^public.ecr.aws/practo/redshiftloader"
- docker images | grep "^public.ecr.aws/practo/redshiftsink"
- make test
