apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: redshiftsink-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redshiftsink-operator-role
subjects:
- kind: ServiceAccount
  name: redshiftsink-operator
  namespace: kube-system
